# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0002_character_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='knowledge',
            new_name='knowledge_index',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='might',
            new_name='might_index',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='sanity',
            new_name='sanity_index',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='speed',
            new_name='speed_index',
        ),
        migrations.AddField(
            model_name='character',
            name='knowledge_options',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='might_options',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='sanity_options',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='speed_options',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
