# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0003_auto_20151229_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
