# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0005_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='knowledge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='might',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='sanity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
